include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_shadowing_type_parameters: true
    avoid_print: false
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_null_checks_in_equality_operators: true

    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_expression_function_bodies: true
    prefer_null_aware_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_interpolation_to_compose_strings: true
    prefer_foreach: true

    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: false
    no_leading_underscores_for_local_identifiers: true
    non_constant_identifier_names: false
    null_check_on_nullable_type_parameter: true
    parameter_assignments: true
    sort_child_properties_last: true
    require_trailing_commas: false
    type_annotate_public_apis: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    use_string_buffers: true


formatter:
  page_width: 120