name: legacy_timeline_scrubber
description: "A highly customizable timeline scrubber widget for Flutter, designed for intuitive navigation through time-based data. Ideal for video players, audio editors, and gantt charts."
version: 1.0.1
homepage: https://github.com/barneysspeedshop/legacy_timeline_scrubber
repository: https://github.com/barneysspeedshop/legacy_timeline_scrubber
screenshots:
  - description: 'Example of the timeline scrubber in action.'
    path: example.gif

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0